# ----
# Site

title: Akreon
url: ""
baseurl:
logo: /images/favicon.png
description: Akreon is building the infrastructure that bridges research advances and safe deployment in autonomous and performance-critical systems.
author:
  name: Akreon
  email: hello@akreon.ai
social:
  name: Akreon
  links: []

# -----
# Build

timezone: Etc/UTC

collections:
  demos:
    output: true
  notes:
    output: true

permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "demos"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
