# ----
# Site

title: Akreon
url: "https://akreon.ai"
baseurl:
logo: /images/favicon.png
description: Akreon studies and builds decision systems under uncertainty.
author:
  name: Akreon
  email: hello@akreon.ai
social:
  name: Akreon
  links:
    - https://akreon.ai

# -----
# Build

timezone: Etc/UTC

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
      layout: "default"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
